version: "3.8"
services:
  backend:
    image: pepti-tools-backend
    container_name: pepti-tools-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/peptitools:/app/peptitools
      - ./backend/config.ini:/app/config.ini
      - ./backend/files/activity_models:/files/activity_models
    ports:
      - "8001:8001"
    restart: "always"
