apiVersion: v1
kind: Pod
metadata:
  labels:
    app: peptitools
  name: pod-peptitools
spec:
  containers:
    - name: backend
      image: peptitools_backend:latest
      envFrom:
        - secretRef:
            name: peptitools
      securityContext:
        runAsUser: 1002
        runAsGroup: 1002
      ports:
        - containerPort: 8000
          hostPort: 10002

    - name: nanotax-frontend
      image: frontend_app:latest
      envFrom:
        - configMapRef:
            name: nanotax
      securityContext:
        runAsUser: 1003
        runAsGroup: 1003
      ports:
        - containerPort: 8080
          hostPort: 10003

  volumes:
    - name: nanotax-db-init
      hostPath:
        path: ./db_init/
        type: DirectoryOrCreate
    - name: nanotax-db-pvc
      persistentVolumeClaim:
        claimName: nanotax-db-pvc
    - name: nanotax-db-tmp
      emptyDir: { }
