FROM python:3.9-slim-bookworm as pfam

RUN apt-get update && \
	apt-get upgrade -y && \
	apt install hmmer gzip wget aria2 -y

# pfam_scan
RUN wget -T 10 https://ftp.ebi.ac.uk/pub/databases/Pfam/Tools/PfamScan.tar.gz && \
	tar -xzf PfamScan.tar.gz && \
	cp -r PfamScan /usr/local/share
WORKDIR /usr/local/share/PfamScan
RUN find . -type f -exec chmod 644 {} + && \
	find . -type d -exec chmod 755 {} + && \
	chmod +x pfam_scan.pl && \
	ln -s /usr/local/share/PfamScan/pfam_scan.pl /usr/local/bin/

# perl dependencies
RUN cpan -T App::cpanminus && \
	cpanm --notest Moose

# data
WORKDIR /usr/local/share/pfam_data
RUN wget https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.dat.gz && \
	gzip -d Pfam-A.hmm.dat.gz
RUN aria2c -x5 --show-console-readout false https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz && \
	gzip -d Pfam-A.hmm.gz && \
	hmmpress Pfam-A.hmm


FROM ghcr.io/astral-sh/uv:0.5-python3.9-bookworm as build

ENV UV_COMPILE_BYTECODE=1

WORKDIR /app
COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock

RUN uv sync -nq --no-dev


FROM python:3.9-slim-bookworm as runtime

ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHOHUNBUFFERED=1

RUN apt-get update && \
	apt-get upgrade -y && \
	apt install hmmer metastudent clustalo gzip git -y && \
	rm -rf /var/lib/apt/lists/*

# copy pfam installation and set env vars
COPY --from=pfam /usr/local /usr/local
ENV PFAM_DB="/usr/local/share/pfam_data/" \
	PERL5LIB="/usr/local/share/PfamScan:${PERL5LIB}"


WORKDIR /app/files
RUN git clone https://github.com/realbigws/Predict_Property
ENV PATH="/app/files/Predict_Property:${PATH}"

COPY . /app/
WORKDIR /app

COPY --from=build /app/.venv /app/.venv

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app

RUN adduser --uid 2001 --system --no-create-home app
USER app

EXPOSE 8000
CMD ["sh", "/app/entrypoint.sh"]
